package  chp5.ex_extends
import cn.lonecloud.drools.bean.Person;
/**  
  * @Package chp5
  * @Description: TODO
  * @author lonecloud
  * @date 2020/2/2310:43 PM
  * @version v1.0
  */
rule "chp5.base"
 salience 60
 when
    $p:Person(age>20);
 then
    System.out.println("年龄大于20岁"+$p);
  end


rule "chp5.ex1" extends "chp5.base"
salience 1000

 when
    $p2:Person(name contains "小");
 then
    System.out.println("名字包含小并且年龄大于20岁"+$p2);
  end